name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the commons repository
      - name: Checkout Commons Repository
        uses: actions/checkout@v4
        with:
          repository: majidbarzegar/commons
          path: commons
          ref: master  # Ensure the master branch is checked out

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # Step 3: Build and install the commons project
      - name: Build Commons Project
        run: |
          cd commons
          mvn clean install -DskipTests
          cd ..

      # Step 4: Verify installed artifacts
      - name: Verify Installed Artifacts
        run: ls -R ~/.m2/repository/com/penovatech

      # Step 5: Check out the main project repository
      - name: Checkout Main Repository
        uses: actions/checkout@v4
        with:
          path: main-project
          ref: master  # Ensure the master branch is checked out

      # Step 6: Build and test the main project
      - name: Build and Test Main Project
        run: |
          cd main-project
          mvn clean install
